const mongoose = require("mongoose");

/**
 * ROUTE SCHEMA
 * Stores optimized routes generated by VROOM with OSRM distance/time data
 */
const RouteSchema = new mongoose.Schema({
  routeId: {
    type: String,
    required: true,
    unique: true,
  },
  // Warehouse starting point
  warehouse: {
    type: mongoose.Schema.Types.ObjectId,
    ref: "Warehouse",
    required: true,
  },
  // Parcels included in this route (ordered sequence)
  parcels: [
    {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Parcel",
    },
  ],
  // Optimized sequence of coordinates (from VROOM)
  optimizedSequence: [
    {
      parcelId: String,
      pickupLocationName: String,
      latitude: Number,
      longitude: Number,
      arrivalTime: Number, // seconds from start
      serviceTime: Number, // time spent at location (seconds)
      distanceFromPrevious: Number, // meters
      travelTimeFromPrevious: Number, // seconds
    },
  ],
  // Route polyline for visualization (encoded or array of coordinates)
  routePolyline: {
    type: mongoose.Schema.Types.Mixed, // Can be encoded string or array of [lng, lat]
    default: [],
  },
  // Return leg polyline (Last parcel to Warehouse)
  returnRoutePolyline: {
    type: mongoose.Schema.Types.Mixed,
    default: [],
  },
  // Total metrics (calculated by OSRM/VROOM)
  totalDistance: {
    type: Number, // in meters
    default: 0,
  },
  totalTime: {
    type: Number, // in seconds
    default: 0,
  },
  estimatedFuelCost: {
    type: Number, // calculated based on distance
    default: 0,
  },
  // Delivery personnel assignment
  assignedDriver: {
    type: mongoose.Schema.Types.ObjectId,
    ref: "Driver",
    default: null,
  },
  // Route status
  status: {
    type: String,
    enum: ["PENDING", "ASSIGNED", "IN_PROGRESS", "COMPLETED", "CANCELLED"],
    default: "PENDING",
  },
  // Lock route to prevent reassignment
  isLocked: {
    type: Boolean,
    default: false,
  },
  // Detailed navigation steps from OSRM
  navigationSteps: [
    {
      distance: Number,
      duration: Number,
      steps: [mongoose.Schema.Types.Mixed], // OSRM step objects
    },
  ],
  // Timestamps
  createdAt: {
    type: Date,
    default: Date.now,
  },
  startedAt: {
    type: Date,
    default: null,
  },
  completedAt: {
    type: Date,
    default: null,
  },
});

module.exports = mongoose.model("Route", RouteSchema);
